"""empty message

Revision ID: 15019badada2
Revises: 38184293555d
Create Date: 2026-02-24 14:57:39.329325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15019badada2'
down_revision = '38184293555d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('optional_email', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.drop_column('optional_email')

    # ### end Alembic commands ###
