"""empty message

Revision ID: 1844858563ac
Revises: 0cbc356eade0
Create Date: 2022-10-30 21:53:58.006226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1844858563ac'
down_revision = '0cbc356eade0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('mobile', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('mobile')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
