"""empty message

Revision ID: 1afe772c89f3
Revises: 1844858563ac
Create Date: 2023-01-24 09:45:24.848597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1afe772c89f3'
down_revision = '1844858563ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_slots', schema=None) as batch_op:
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_slots', schema=None) as batch_op:
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
