"""empty message

Revision ID: 3515fb04a35c
Revises: ad2009188a02
Create Date: 2022-02-07 09:50:37.461073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3515fb04a35c'
down_revision = 'ad2009188a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slots', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slots', 'completed')
    # ### end Alembic commands ###
