"""empty message

Revision ID: 35e3fa4ba0ba
Revises: f3014a2b4031
Create Date: 2022-02-07 16:29:05.843674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e3fa4ba0ba'
down_revision = 'f3014a2b4031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_slots', sa.Column('class_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class_slots', 'class_description')
    # ### end Alembic commands ###
