"""Add non-Nullable Instructor field

Revision ID: 38184293555d
Revises: 17f7848370ef
Create Date: 2023-01-26 11:41:16.135269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38184293555d'
down_revision = '17f7848370ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.alter_column('instructor',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.execute("UPDATE slots SET instructor = 'TBC'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.alter_column('instructor',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###
