"""make capacity non-nullable, complete addition of user_id

Revision ID: 6094b41e4468
Revises: a10766ff9aea
Create Date: 2022-10-04 17:08:39.442033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6094b41e4468'
down_revision = 'a10766ff9aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE class_slots SET capacity = 6")
    with op.batch_alter_table('class_slots', schema=None) as batch_op:
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_slots', schema=None) as batch_op:
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
