"""make capacity non-nullable, complete addition of user_id

Revision ID: 6094b41e4468
Revises: a10766ff9aea
Create Date: 2022-10-04 17:08:39.442033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6094b41e4468'
down_revision = 'a10766ff9aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE class_slots SET capacity = 6")
    with op.batch_alter_table('class_slots', schema=None) as batch_op:
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_students_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_students_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('class_slots', schema=None) as batch_op:
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
