"""Add capacity to ClassSlot

Revision ID: 6ec5d8e9aae8
Revises: 7d35fe0ef1c9
Create Date: 2022-10-04 14:37:43.683518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec5d8e9aae8'
down_revision = '7d35fe0ef1c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_slots', sa.Column('capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class_slots', 'capacity')
    # ### end Alembic commands ###
