"""Add waiver_returned to User

Revision ID: 7d35fe0ef1c9
Revises: 35e3fa4ba0ba
Create Date: 2022-10-04 14:35:09.539136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d35fe0ef1c9'
down_revision = '35e3fa4ba0ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('waiver_returned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'waiver_returned')
    # ### end Alembic commands ###
