"""empty message

Revision ID: 89b351c62297
Revises: 7fc0e9667dd4
Create Date: 2022-02-07 14:38:53.835342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b351c62297'
down_revision = '7fc0e9667dd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_slots', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class_slots', 'completed')
    # ### end Alembic commands ###
