"""Add user_id to Student

Revision ID: a10766ff9aea
Revises: 6ec5d8e9aae8
Create Date: 2022-10-04 14:48:39.263199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a10766ff9aea'
down_revision = '6ec5d8e9aae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('students', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_students_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('students', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_students_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')


    # ### end Alembic commands ###
