"""empty message

Revision ID: b730bc742b80
Revises: 363b74490255
Create Date: 2022-02-07 08:12:48.438295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b730bc742b80'
down_revision = '363b74490255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slots', sa.Column('comment', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slots', 'comment')
    # ### end Alembic commands ###
