"""empty message

Revision ID: f3014a2b4031
Revises: 89b351c62297
Create Date: 2022-02-07 14:54:04.652008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3014a2b4031'
down_revision = '89b351c62297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_slots', sa.Column('class_name', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class_slots', 'class_name')
    # ### end Alembic commands ###
